# Site settings
title: Weitao Wang's Homepage
SEOTitle: Weitao Wang's Homepage
header-img: img/home-bg.jpg
email: wtwang@rice.com
description: "Contact: wtwang AT rice.edu"
keyword: "Weitao Wang, Rice University, Programmable Hardware, Heterogeneous System, Distributed System, Data Center Network, Optical Network Architecture"
url: "https://weitaowang.site"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     
github_username: Clark5
# twitter_username:   
# facebook_username:  
linkedin_username:  weitao-wang-496464121



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: redcarpet
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  hard_wrap: true
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: weitao

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-197242560-1'            # Format: UA-xxxxxx-xx
ga_domain: weitaowang.site



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "My name is Weitao Wang, a third-year PhD student at Rice Univ. Please check the about me page for more information."
sidebar-avatar: /img/wwt.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
  {
    title: "Liangcheng Yu",
    href: "https://liangchengyu.com/"
  },
  {
    title: "Yaowei Huang",
    href: "https://huangyaowei.github.io/"
  },{
    title: "Jiefeng Li",
    href: "https://jeffli.site/"
  },{
    title: "Fengyu Deng",
    href: "https://github.com/DFY8054"
  },{
    title: "Hao Wu",
    href: "https://scholar.google.com/citations?user=xKwVyZkAAAAJ&hl=en"
  },{
    title: "Yucheng Yang",
    href: "https://scholar.google.com/citations?user=Ik7LI4EAAAAJ&hl=en"
  },{
    title: "Jiachen Sun",
    href: "https://web.eecs.umich.edu/~jiachens/"
  },{
    title: "Shuheng Liao",
    href: "https://www.linkedin.com/in/shuheng-liao-290117155/"
  },{
    title: "Dingming Wu",
    href: "https://dmwu.github.io/"
  },{
    title: "Jiarong Xing",
    href: "https://jxing.me/"
  },{
    title: "Qiao Kang",
    href: "https://qiaokang.org/"
  },{
    title: "Sushovan Das",
    href: "https://www.linkedin.com/in/sushovan-das-5aa913a9/"
  }
]
